export { default as Navbar } from "./Navbar";
export { default as HeroSection } from "./HeroSection";
export { default as LogosSection } from "./LogosSection";
export { default as FeaturesSection } from "./FeaturesSection";
export { default as StatsSection } from "./StatsSection";
export { default as TestimonialsSection } from "./TestimonialsSection";
export { default as PricingSection } from "./PricingSection";
export { default as CTASection } from "./CTASection";
export { default as Footer } from "./Footer";
