export const invoiceInitialValue = {
  case: null,
  matter: null,
  client: "",
  title: "",
  description: "",
  services: [
    {
      description: "",
      billingMethod: "hourly",
      hours: 0,
      rate: 0,
      fixedAmount: 0,
      quantity: 1,
      unitPrice: 0,
      amount: 0,
      date: null,
      category: "other",
    },
  ],
  expenses: [
    {
      description: "",
      amount: 0,
      date: null,
      category: "other",
      receiptNumber: "",
      isReimbursable: true,
    },
  ],
  dueDate: null,
  billingPeriodStart: null,
  billingPeriodEnd: null,
  discount: 0,
  discountType: "none",
  discountReason: "",
  taxRate: 0,
  previousBalance: 0,
  subtotal: 0,
  taxAmount: 0,
  total: 0,
  amountPaid: 0,
  balance: 0,
  paymentTerms: "Net 30 days",
  notes: "",
  internalNotes: "",
  matterReference: "",
  status: "draft",
  issueDate: null,
};

export const paymentInitialValue = {
  invoice: null,
  client: null,
  case: null,
  matter: null,
  amount: 0,
  method: "bank_transfer",
  paymentDate: null,
  reference: "",
  notes: "",
  status: "completed",
  transactionId: "",
};

export const caseInitialValue = {
  firstParty: {
    description: "",
    name: [],
    processesFiled: [],
  },
  secondParty: {
    description: "",
    name: [],
    processesFiled: [],
  },
  otherParty: [
    {
      description: "",
      name: [],
      processesFiled: [],
    },
  ],
  suitNo: "",
  caseOfficeFileNo: "",
  courtName: "",
  courtNo: "",
  location: "",
  otherCourt: "",
  judge: [],
  caseSummary: "",
  caseStatus: "",
  natureOfCase: "",
  category: "",
  isFiledByTheOffice: false,
  filingDate: "",
  modeOfCommencement: "",
  otherModeOfCommencement: "",
  caseStrengths: [],
  caseWeaknesses: [],
  casePriority: "",
  stepToBeTaken: [],
  caseUpdates: [],
  accountOfficer: [],
  client: [],
  generalComment: "",
};

export const addUserInitValue = {
  firstName: "",
  lastName: "",
  secondName: "",
  middleName: "",
  email: "",
  password: "",
  passwordConfirm: "",
  gender: "",
  address: "",
  bio: "",
  role: "",
  position: "",
  annualLeaveEntitled: "",
  phone: "",
  isLawyer: false,
  clientCase: [],
  yearOfCall: "",
  otherPosition: "",
  practiceArea: "",
  universityAttended: "",
  lawSchoolAttended: "",
};
